# GET ALL PARAMETERS USABLE FOR CUSTOM CONFIG BY RUNNING:
## --------------------------------------------------------------
## |          rosrun mrs_uav_core get_public_params.py          #
## --------------------------------------------------------------

mrs_uav_managers:

  control_manager:

    trackers: [
      "FlipTracker"
    ]

    safety:

      tilt_limit:
      
        eland:
          enabled: false
          limit: 75.0 # [deg]

        disarm:
          enabled: false
          limit: 75.0 # [deg]

      tilt_error_disarm:
        enabled: false
        timeout: 0.5 # [s] # for how long the error has to be present to disarm
        error_threshold: 20.0 # [deg]

      yaw_error_eland:
        enabled: false
        limit: 90.0 # [deg]

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    takeoff:

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "Se3Controller"
        tracker: "MpcTracker"

    midair_activation:

      after_activation:
        controller: "Se3Controller"
        tracker: "MpcTracker"

  constraint_manager:

    # list of allowed constraints per odometry mode
    allowed_constraints:
      gps_baro: ["slow", "medium", "fast"]

    # those constraints will be used automatically when a localization mode switches
    # and the current constraints are not in the allowed list (next paragraphs)
    default_constraints:
      gps_baro: "fast"
