input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         true
  attitude:              true
  acceleration_hdg_rate: false
  acceleration_hdg:      false
  velocity_hdg_rate:     false
  velocity_hdg:          false
  position:              false

  feedforward: true

outputs:
  distance_sensor:      false
  gnss:                 true
  rtk:                  false
  imu:                  true
  altitude:             true
  magnetometer_heading: true
  rc_channels:          true
  battery_state:        true
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             false
  ground_truth:         false



serial_port: "/dev/ttyUSB0"
baud_rate: 2000000

start_latitude: 15.2
start_longditude: 14.3