simulation_rate: 1000
clock_rate: 1000
realtime_factor: 1.0

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

uav_names: [
  "uav1",
]

uav1:
  type: "f450"
  spawn:
    x: 10.0
    y: 15.0
    z: 2.0
    heading: 0
