world_origin:

  units: "UTM" # {"UTM, "LATLON"}

  origin_x: 0
  origin_y: 0

safety_area:

  enabled: false

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "world_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      -50, -50,
      50,  -50,
      50,  50,
      -50, 50,
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 15.0
    min_z: 0.5
